export enum PathsEnum {
    login = '/login',
    register = '/register',
    dashboard = '/dashboard',
    customers = '/customers',
    affiliates = '/affiliates',
    affiliatesRegister = '/affiliates/register',
    vehicles = '/vehicles',
    rates = '/rates',
    liveMonitoring = '/live-monitoring',
    tripHistory = '/trip-history',
    ratings = '/ratings',
    support = '/support',
    reports = '/reports',
    settings = '/settings',
    benefits = '/benefits',
}
